arb-dir: lib/features/localization/l10n
template-arb-file: app_en.arb
output-localization-file: app_localizations.dart
untranslated-messages-file: untranslated_messages.txt
preferred-supported-locales:
  - en
  - tr
  - ar
  - de